language: node_js

node_js:
  - "4.0"

sudo: false

install: 
- npm install
- npm install -g grunt-cli
- npm install -g npm@'>=2.13.5'

env:
  global:
  - GH_REF: github.com/ScottLogic/d3fc.git
  - secure: "dimY26/YND+hamNAH6lwjYqkmc4qEkSDPl8xwe7wJxliR8k8cPM8lRw8c/Iwtmq3NiG5cZoiKAkALA4PTl3zQ7YOj7rSL9pGmi4qJvtObqWljclJjY/0sNprPc/RrRTgpBcnI3Pa7fofiT2uLNp+a0mT/KV9KZNxjQIw8PA2RkY="
after_success: bash ./site/deploy.sh

deploy:
  - provider: npm
    email: price.c@gmail.com
    api_key:
      secure: "A0JeRqeOUJXxMuwVUlJ0JqrmWB+RbuECIQ6dEJoDaeQEKatUKP3uVtTn0sO1xyvHBUtkS2ImnnOjIJ2XGcnACjoPU58/E88ICcTOBhTBfplHi78e/mYTYIM7o3VOTWud+3aAsfw7O7YrmOLnhe1Dm65TQKxXH9EfoYLIbta7+9Q="
    skip_cleanup: true
    on:
      branch: master
      tags: true
  - provider: releases
    api_key:
      secure: "anji1SlRHf9kXmQ4M1L0/Y3s+vXtvDuKKk02VBsWPcIBDFPcSmK+C9DBRAKUq6953C1cImUf/GvKlh1zHKkiLz0mG0zoovufrflThk2rxQqnIJ9Ec6Igmh5us32DVxEcTNyXBJFNeHsMB1Wg5PkOffYbEr+e+wxgoCQKpDXMR7k="
    file:
      - "dist/d3fc.css"
      - "dist/d3fc.js"
      - "dist/d3fc.min.css"
      - "dist/d3fc.min.js"
      - "dist/d3fc.min.js.map"
    skip_cleanup: true
    on:
      branch: master
      tags: true
