component-ids: [chart, series, indicator, scale, svg, annotation, tool, layout, data]

components:
  annotation:
    name: Annotations
  chart:
    name: Chart
  series:
    name: Series
  indicator:
    name: Indicators
  scale:
    name: Scale
  tool:
    name: Tools
  svg:
    name: SVG
  layout:
    name: Layout
  data:
    name: Data
